# -- Site Configuration --
# -- Development --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = ["hugo-video", 'blowfish', 'plugin-glightbox']
baseURL = "https://emredogan.co.uk/"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

timeout = 60000

buildDrafts = false
buildFuture = false

googleAnalytics = "G-MZETEW0XZT"

[imaging]
anchor = 'Center'

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = 'daily'
filename = 'sitemap.xml'
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]

[module]
[module.hugoVersion]
extended = false
min = "0.112.0"
# [[module.mounts]]
# source = "assets"
# target = "assets"
# [[module.mounts]]
# source = "hugo_stats.json"
# target = "assets/watching/hugo_stats.json"
[[module.imports]]
path = "github.com/davidsneighbour/hugo-debug"
disable = false
ignoreConfig = false
ignoreImports = false

# [build]
# [build.buildStats]
# enable = true
# [[build.cachebusters]]
# source = 'assets/watching/hugo_stats\.json'
# target = 'main\.css'
# [[build.cachebusters]]
# source = '(postcss|tailwind)\.config\.js'
# target = 'css'
# [[build.cachebusters]]
# source = 'assets/.*\.(js|ts|jsx|tsx)'
# target = 'js'
# [[build.cachebusters]]
# source = 'assets/.*\.(.*)$'
# target = '$1'
